# Generated by Django 3.1.4 on 2020-12-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='data',
            new_name='date',
        ),
    ]
