# Generated by Django 3.1.4 on 2020-12-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20201206_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='text',
        ),
    ]
